name: build

on: [push, pull_request]

jobs:
  release-versions:
    name: Build on ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install BLAS and LAPACK
        run: sudo apt-get install -y libopenblas-dev liblapacke-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install --no-document bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake

  ruby-head:
    name: Build on ruby-head
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'debug' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install BLAS and LAPACK
        run: sudo apt-get install -y libopenblas-dev liblapacke-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install --no-document bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
